on:
  push:
    branches:
      - main

name: ğŸš€ Deploy website on push

jobs:
  setup:
    name: ğŸ› ï¸ Setup
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v2

    - name: ğŸ› ï¸ Install Hugo
      run: |
        sudo apt-get install hugo

  generate-public:
    name: ğŸ“‚ Generate Public Folder
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v2

    - name: ğŸ› ï¸ Install Hugo
      run: |
        sudo apt-get install hugo

    - name: ğŸ“‚ Generate Hugo public folder
      run: hugo

    - name: ğŸ“‚ Show public folder
      run: ls -lhart

  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    needs: generate-public
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v2

    - name: ğŸ› ï¸ Install Hugo
      run: |
        sudo apt-get install hugo

    - name: ğŸ“‚ Generate Hugo public folder
      run: hugo

    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.ftp_host }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        local-dir: ./public_teala/
        server-dir: andersonteala.hamstercode.com.br/

  # send-telegram-message:
  #   name: ğŸ“¬ Send Telegram Message
  #   runs-on: ubuntu-latest
  #   needs: [web-deploy]
  #   steps:
  #   - name: ğŸ¤– Send Message
  #     uses: appleboy/telegram-action@v0.2.0
  #     with:
  #       to: ${{ secrets.telegram_chat_id }}
  #       token: ${{ secrets.telegram_bot_token }}
  #       message: "âœ… Deployed successfully, check it out at https://andersonteala.hamstercode.com.br"